/*UTILIZADO PARA TESTES*/
DROP DATABASE IF EXISTS BACKUP;

/*CRIAR A DATABASE DO BAR*/
CREATE DATABASE IF NOT EXISTS BACKUP;
USE BACKUP;

/*TABELA GUARDA OS DEPARTAMENTOS EXISTENTES NA EMPRESA */
CREATE TABLE IF NOT EXISTS BKP_DEPARTAMENTO(
     ID_BACKUP INT PRIMARY KEY AUTO_INCREMENT,
     ID_DEPARTAMENTO INT,
     DEPARTAMENTO VARCHAR(50) NOT NULL UNIQUE,
	 DESCRICAO VARCHAR (100) NOT NULL,
     DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO ENUM ('DELETE','INSERE','UPDATE')
     );
     
/*TABELA GUARDA DADOS DOS FUNCIONARIOS */
CREATE TABLE IF NOT EXISTS BKP_FUNCIONARIO(
     ID_BACKUP INT PRIMARY KEY AUTO_INCREMENT,
     ID_FUNCIONARIO INT,
     NOME VARCHAR(50) NOT NULL,
     SOBRENOME VARCHAR(50) NOT NULL, 
	 DATA_NASCIMENTO DATE NOT NULL,
     SEXO ENUM('M','F') NOT NULL,
     CPF VARCHAR(15) NOT NULL UNIQUE,
     RG VARCHAR(15) NOT NULL UNIQUE, 
     ID_DEPARTAMENTO INT, 
     DATA DATETIME,
	 USUARIO VARCHAR(30),
	 EVENTO ENUM ('DELETE','INSERE','UPDATE')
   
 	 );
     
/*TABELA GUARDA DADOS DOS CLIENTES DA EMPRESA*/
CREATE TABLE IF NOT EXISTS BKP_CLIENTE(
     ID_BACKUP INT PRIMARY KEY AUTO_INCREMENT,
     ID_CLIENTE INT,
     NOME VARCHAR(100) NOT NULL,
	 SOBRENOME VARCHAR(100) NOT NULL,
	 CPF VARCHAR(11) UNIQUE,
	 RG VARCHAR(15) NOT NULL,
	 DATA_NASCIMENTO DATE NOT NULL,
	 DATA_CADASTRO DATE NOT NULL, 
     SEXO ENUM('M','F') NOT NULL,
     DATA DATETIME,
	 USUARIO VARCHAR(30),
	 EVENTO ENUM ('DELETE','INSERE','UPDATE')
	 );
     
/*TABELA GUARDA AS INFORMACOES DOS FORNECEDORES*/
CREATE TABLE IF NOT EXISTS BKP_FORNECEDOR(
	ID_BACKUP INT PRIMARY KEY AUTO_INCREMENT, 
    ID_FORNECEDOR INT, 
    RAZAO_SOCIAL VARCHAR(50) NOT NULL, 
    NOME_FANTASIA VARCHAR(50) NOT NULL,
    CNPJ VARCHAR(14) NOT NULL UNIQUE, 
    INSC_ESTADUAL VARCHAR(20) NOT NULL,
    DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO ENUM ('DELETE','INSERE','UPDATE')
);

/*TABELA GUARDA OS TELEFONES DA EMPRESA*/
CREATE TABLE IF NOT EXISTS BKP_TELEFONE(
	ID_BACKUP INT PRIMARY KEY AUTO_INCREMENT,
    ID_TELEFONE INT,
    TELEFONE VARCHAR(25),
    B_CELULAR BOOL,
    B_WHATSAPP BOOL,
    
    ID_CLIENTE INT , 
    ID_FUNCIONARIO INT, 
    ID_FORNECEDOR INT,
    
    DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO ENUM ('DELETE','INSERE','UPDATE')
  
    
);

/*TABELA GUARDA OS EMAILS DA EMPRESA*/
CREATE TABLE IF NOT EXISTS BKP_EMAIL(
	ID_BACKUP INT PRIMARY KEY AUTO_INCREMENT,
    ID_EMAIL INT,
    EMAIL VARCHAR(25),
    
    ID_CLIENTE INT , 
    ID_FUNCIONARIO INT, 
    ID_FORNECEDOR INT,
    
	DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO ENUM ('DELETE','INSERE','UPDATE')    
    
);

/*TABELA GUARDA OS INSTAGRAM DOS CLIENTES DA EMPRESA*/
CREATE TABLE IF NOT EXISTS BKP_INSTAGRAM(
	ID_BACKUP INT PRIMARY KEY AUTO_INCREMENT,
    ID_INSTAGRAM INT,
    INSTAGRAM VARCHAR(25),
    ID_CLIENTE INT,
    DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO ENUM ('DELETE','INSERE','UPDATE')    
    
);

/*TABELA GUARDA OS PAISES PARA ENDERECO*/
CREATE TABLE IF NOT EXISTS BKP_PAIS(
	ID_BACKUP INT PRIMARY KEY AUTO_INCREMENT,
    ID_PAIS INT,
    PAIS VARCHAR(30) NOT NULL,
    DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO ENUM ('DELETE','INSERE','UPDATE')
);

/*TABELA GUARDA OS ESTADOS DOS PAISES PARA ENDERECO*/
CREATE TABLE IF NOT EXISTS BKP_ESTADO(
	ID_BACKUP INT PRIMARY KEY AUTO_INCREMENT,
    ID_ESTADO INT,
    ESTADO VARCHAR(30) NOT NULL, 
    ID_PAIS INT,
	DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO ENUM ('DELETE','INSERE','UPDATE')    
	
);

/*TABELA GUARDA AS CIDADES DOS ESTADOS DOS PAISES PARA ENDERECO*/
CREATE TABLE IF NOT EXISTS BKP_CIDADE(
	ID_BACKUP INT PRIMARY KEY AUTO_INCREMENT,
    ID_CIDADE INT,
    CIDADE VARCHAR(30) NOT NULL, 
    
    ID_PAIS INT,
    ID_ESTADO INT,
    
    DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO ENUM ('DELETE','INSERE','UPDATE')	 
	
);

/*TABELA GUARDA OS BAIRROS DAS CIDADES DOS ESTADOS DOS PAISES PARA ENDERECO*/
CREATE TABLE IF NOT EXISTS BKP_BAIRRO(
	ID_BACKUP INT PRIMARY KEY AUTO_INCREMENT,
    ID_BAIRRO INT,
    BAIRRO VARCHAR(30) NOT NULL, 
    
    ID_PAIS INT,
    ID_ESTADO INT,
    ID_CIDADE INT,
    DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO ENUM ('DELETE','INSERE','UPDATE')	 
	
);

/*TABELA GUARDA AS BATIDAS DE PONTO DOS FUNCIONARIOS*/
CREATE TABLE IF NOT EXISTS BKP_LISTA_PONTO(
     ID_BACKUP INT PRIMARY KEY AUTO_INCREMENT,
     ID_PONTO INT,
     HORAS TIME(6) NOT NULL,
	 DATA DATE NOT NULL,
	 ID_FUNCIONARIO INT,
     USUARIO VARCHAR(30),
	 EVENTO ENUM ('DELETE','INSERE','UPDATE')	 
	 
     );
     
/*TABELA GUARDA OS PEDIDOS PARA CONSUMO LOCAL E ENTREGA*/
CREATE TABLE IF NOT EXISTS BKP_PEDIDO(
	
    ID_BACKUP INT PRIMARY KEY AUTO_INCREMENT, 
    ID_PEDIDO INT, 
    VALOR_TOTAL FLOAT NOT NULL, 
    QUANT_ITENS INT NOT NULL, 
    MESA INT, 
	DATA DATE NOT NULL, 
    HORA TIME NOT NULL, 
    STATUS ENUM('P','E') NOT NULL, /*PRESENCIAL OU ENTREGA*/
    ID_CLIENTE INT, 
    ID_FUNCIONARIO INT, 
    USUARIO VARCHAR(30),
	EVENTO ENUM ('DELETE','INSERE','UPDATE')     
    
);

/*TABELA GUARDA AS INFORMAÇÕES DAS MOTOS DE ENTREGA*/
CREATE TABLE IF NOT EXISTS BKP_MOTO(
	ID_BACKUP INT PRIMARY KEY AUTO_INCREMENT, 
    ID_MOTO INT, 
    PLACA VARCHAR(15) NOT NULL, 
    RENAVAN VARCHAR(30) NOT NULL, 
    ANO_FABRICACAO YEAR NOT NULL, 
    DATA_COMPRA DATE NOT NULL, 
    DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO ENUM ('DELETE','INSERE','UPDATE')
    
);

/*TABELA GUARDA AS INFORMAÇÕES DE PAGAMENTO*/
CREATE TABLE IF NOT EXISTS BKP_PAGAMENTO(
	ID_BACKUP INT PRIMARY KEY AUTO_INCREMENT, 
    ID_PAGAMENTO INT, 
    TIPO_PAGAMENTO ENUM('CREDITO','DEBITO', 'DINHEIRO', 'PIX') NOT NULL, 
    VALOR_ENTREGA FLOAT,
    VALOR_TOTAL FLOAT,
    
    ID_PEDIDO INT, 
    
    DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO ENUM ('DELETE','INSERE','UPDATE')    
    
   
);

/*TABELA GUARDA AS QUANTIDADES DE MATERIA-PRIMA EM ESTOQUE*/
CREATE TABLE IF NOT EXISTS BKP_MATERIA_PRIMA(
	ID_BACKUP INT PRIMARY KEY AUTO_INCREMENT, 
    ID_MATERIA_PRIMA INT, 
    NOME VARCHAR(50) NOT NULL, 
    DESCRICAO VARCHAR(200), 
    QUANTIDADE FLOAT NOT NULL,
    VALOR_MEDIO FLOAT NOT NULL, 
    TIPO ENUM('UNIDADE','GRAMAS', 'QUILOGRAMA') NOT NULL,
    DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO ENUM ('DELETE','INSERE','UPDATE')
);


/*TABELA GUARDA AS CATEGORIAS DE ITENS DO MENU*/
CREATE TABLE IF NOT EXISTS BKP_CATEGORIA(
	ID_BACKUP INT PRIMARY KEY AUTO_INCREMENT,
    ID_CATEGORIA INT,
    NOME VARCHAR(50) NOT NULL, 
    DESCRICAO VARCHAR(100),
    DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO ENUM ('DELETE','INSERE','UPDATE')
);

/*TABELA GUARDA OS ITENS NO MENU*/
CREATE TABLE IF NOT EXISTS BKP_ITEM_MENU(
	ID_BACKUP INT PRIMARY KEY AUTO_INCREMENT, 
    ID_ITEM_MENU INT, 
    NOME VARCHAR(50) NOT NULL, 
    DESCRICAO VARCHAR(200), 
    CAMINHO_IMAGEM VARCHAR(150),
    VALOR FLOAT,
    
    ID_CATEGORIA INT,
    
    DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO ENUM ('DELETE','INSERE','UPDATE')    
  
);

/*TABELA GUARDA A LISTA DE PRODUTOS DO PEDIDO*/
CREATE TABLE IF NOT EXISTS BKP_LISTA_PRODUTOS_PEDIDO(
	ID_BACKUP INT PRIMARY KEY AUTO_INCREMENT,
    ID_LISTA_PRODUTOS_PEDIDO INT ,
	ID_PEDIDO INT, 
    ID_ITEM_MENU INT,
    
    QUANTIDADE INT,
    VALOR FLOAT, 
    
    DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO ENUM ('DELETE','INSERE','UPDATE')    
   
);

/*TABELA ONDE SE GUARDA AS ORDENS DE COMPRA*/
CREATE TABLE IF NOT EXISTS BKP_ORDEM_COMPRA(
	ID_BACKUP INT PRIMARY KEY AUTO_INCREMENT, 
    ID_ORDEM_COMPRA INT, 
    OBSERVACAO VARCHAR(100), 
    QUANTIDADE_ITENS INT NOT NULL,
    VALOR_TOTAL FLOAT, 
    TIPO_PAGAMENTO ENUM('CREDITO','DEBITO', 'DINHEIRO', 'PIX') NOT NULL, 

    ID_FUNCIONARIO INT, 
    ID_FORNECEDOR INT, 
    
    DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO ENUM ('DELETE','INSERE','UPDATE')
    
);

/*TABELA GUARDA O ENDERECO DE CLIENTES E FUNCIONARIO*/
CREATE TABLE IF NOT EXISTS BKP_ENDERECO(
     ID_BACKUP INT PRIMARY KEY AUTO_INCREMENT,
     ID_ENDERECO INT,
     ENDERECO VARCHAR(30) NOT NULL,
     NUMERO INT,

     ID_FUNCIONARIO INT,
	 ID_CLIENTE INT,
     ID_FORNECEDOR INT, 
     
     DATA DATETIME,
	 USUARIO VARCHAR(30),
	 EVENTO ENUM ('DELETE','INSERE','UPDATE'),	    
	 ID_PAIS INT,
     ID_ESTADO INT,
     ID_CIDADE INT,
     ID_BAIRRO INT	 
	
	 );	

/*TABELA GUARDA A LISTA DE PRODUTOS EM CADA COMPRA*/
CREATE TABLE IF NOT EXISTS BKP_LISTA_PRODUTOS_COMPRA(
	ID_BACKUP INT PRIMARY KEY AUTO_INCREMENT,
    ID_ORDEM_COMPRA INT,
    ID_MATERIA_PRIMA INT, 
    QUANTIDADE INT NOT NULL, 
    VALOR FLOAT NOT NULL, 
	DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO ENUM ('DELETE','INSERE','UPDATE')    
    
);

/*TABELA GUARDA AS DEMANDAS DE MATERIA PRIMA PARA MENU*/
CREATE TABLE IF NOT EXISTS BKP_DEMANDA(
	ID_BACKUP INT PRIMARY KEY AUTO_INCREMENT,
    ID_DEMANDA INT,
    QUANTIDADE FLOAT,
    
    ID_ITEM_MENU INT, 
    ID_MATERIA_PRIMA INT,
    
    DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO ENUM ('DELETE','INSERE','UPDATE')    
    
);

/*TABELA GUARDA AS INFORMAÇÕESD E ENTREGA*/
CREATE TABLE IF NOT EXISTS BKP_ENTREGA(
	ID_BACKUP INT PRIMARY KEY AUTO_INCREMENT, 
    ID_ENTREGA INT, 
    ROTA VARCHAR(200), 

    ID_ENDERECO INT,
    
    ID_FUNCIONARIO INT, 
    ID_PEDIDO INT, 
    ID_MOTO INT, 
    
    DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO ENUM ('DELETE','INSERE','UPDATE')    
    
);
     
     