/*CREATE DATABASE BACKUP;*/
USE BAR_PETISCARIA_ARV_DATABASE;

/* GATILHO DE BACKUP DA TABELA DEPARTAMENTO */
DELIMITER $$
CREATE TRIGGER BKP_DEPARTAMENTO
AFTER INSERT ON DEPARTAMENTO
FOR EACH ROW
BEGIN
    INSERT INTO BACKUP.BKP_DEPARTAMENTO (ID_DEPARTAMENTO, DEPARTAMENTO, DESCRICAO)
    VALUES (NEW.ID_DEPARTAMENTO, NEW.DEPARTAMENTO, NEW.DESCRICAO);
END$$
DELIMITER ;

/* GATILHO DE BACKUP DA TABELA FUNCIONÁRIO */
DELIMITER $$
CREATE TRIGGER BKP_FUNCIONARIO
AFTER INSERT ON FUNCIONARIO
FOR EACH ROW
BEGIN
    INSERT INTO BACKUP.BKP_FUNCIONARIO (ID_FUNCIONARIO, NOME, SOBRENOME, DATA_NASCIMENTO, SEXO, CPF, RG, ID_DEPARTAMENTO, DATA, USUARIO, EVENTO)
    VALUES (NEW.ID_FUNCIONARIO, NEW.NOME, NEW.SOBRENOME, NEW.DATA_NASCIMENTO, NEW.SEXO, NEW.CPF, NEW.RG, NEW.ID_DEPARTAMENTO, NOW(), CURRENT_USER(), "INSERE");
END$$
DELIMITER ;

/* GATILHO DE BACKUP DA TABELA CLIENTE */
DELIMITER $$
CREATE TRIGGER BKP_CLIENTE
AFTER INSERT ON CLIENTE
FOR EACH ROW
BEGIN
    INSERT INTO BACKUP.BKP_CLIENTE (ID_CLIENTE, NOME, SOBRENOME, CPF, RG, DATA_NASCIMENTO, DATA_CADASTRO, SEXO)
    VALUES (NEW.ID_CLIENTE, NEW.NOME, NEW.SOBRENOME, NEW.CPF, NEW.RG, NEW.DATA_NASCIMENTO, NEW.DATA_CADASTRO, NEW.SEXO);
END$$
DELIMITER ;

/* GATILHO DE BACKUP DA TABELA FORNECEDOR */
DELIMITER $$
CREATE TRIGGER BKP_FORNECEDOR
AFTER INSERT ON FORNECEDOR
FOR EACH ROW
BEGIN
    INSERT INTO BACKUP.BKP_FORNECEDOR (ID_FORNECEDOR, RAZAO_SOCIAL, NOME_FANTASIA, CNPJ, INSC_ESTADUAL)
    VALUES (NEW.ID_FORNECEDOR, NEW.RAZAO_SOCIAL, NEW.NOME_FANTASIA, NEW.CNPJ, NEW.INSC_ESTADUAL);
END$$
DELIMITER ;

/* GATILHO DE BACKUP DA TABELA TELEFONE */
DELIMITER $$
CREATE TRIGGER BKP_TELEFONE
AFTER INSERT ON TELEFONE
FOR EACH ROW
BEGIN
INSERT INTO BACKUP.BKP_TELEFONE (ID_TELEFONE, TELEFONE, B_CELULAR, B_WHATSAPP, ID_CLIENTE, ID_FUNCIONARIO, ID_FORNECEDOR)
VALUES (NEW.ID_TELEFONE, NEW.TELEFONE, NEW.B_CELULAR, NEW.B_WHATSAPP, NEW.ID_CLIENTE, NEW.ID_FUNCIONARIO, NEW.ID_FORNECEDOR);
END$$
DELIMITER ;

/* GATILHO DE BACKUP DA TABELA EMAIL */
DELIMITER $$
CREATE TRIGGER BKP_EMAIL
AFTER INSERT ON EMAIL
FOR EACH ROW
BEGIN
    INSERT INTO BACKUP.BKP_EMAIL (ID_EMAIL, EMAIL, ID_CLIENTE, ID_FUNCIONARIO, ID_FORNECEDOR)
    VALUES (NEW.ID_EMAIL, NEW.EMAIL, NEW.ID_CLIENTE, NEW.ID_FUNCIONARIO, NEW.ID_FORNECEDOR);
END$$
DELIMITER ;

/* GATILHO DE BACKUP DA TABELA INSTAGRAM */
DELIMITER $$
CREATE TRIGGER BKP_INSTAGRAM
AFTER INSERT ON INSTAGRAM
FOR EACH ROW
BEGIN
    INSERT INTO BACKUP.BKP_INSTAGRAM (ID_INSTAGRAM, INSTAGRAM, ID_CLIENTE)
VALUES (NEW.ID_INSTAGRAM, NEW.INSTAGRAM, NEW.ID_CLIENTE);
END$$
DELIMITER ;

/* GATILHO DE BACKUP DA TABELA PAIS */
DELIMITER $$
CREATE TRIGGER BKP_PAIS
AFTER INSERT ON PAIS
FOR EACH ROW
BEGIN
INSERT INTO BACKUP.BKP_PAIS (ID_PAIS, PAIS)
VALUES (NEW.ID_PAIS, NEW.PAIS);
END$$
DELIMITER ;

/* GATILHO DE BACKUP DA TABELA ESTADO */
DELIMITER $$
CREATE TRIGGER BKP_ESTADO
AFTER INSERT ON ESTADO
FOR EACH ROW
BEGIN
INSERT INTO BACKUP.BKP_ESTADO (ID_ESTADO, ESTADO, ID_PAIS)
VALUES (NEW.ID_ESTADO, NEW.ESTADO, NEW.ID_PAIS);
END$$
DELIMITER ;

/* GATILHO DE BACKUP DA TABELA CIDADE */
DELIMITER $$
CREATE TRIGGER BKP_CIDADE
AFTER INSERT ON CIDADE
FOR EACH ROW
BEGIN
INSERT INTO BACKUP.BKP_CIDADE (ID_CIDADE, CIDADE, ID_PAIS, ID_ESTADO)
VALUES (NEW.ID_CIDADE, NEW.CIDADE, NEW.ID_PAIS, NEW.ID_ESTADO);
END$$
DELIMITER ;

/* GATILHO DE BACKUP DA TABELA BAIRRO */
DELIMITER $$
CREATE TRIGGER BKP_BAIRRO
AFTER INSERT ON BAIRRO
FOR EACH ROW
BEGIN
INSERT INTO BACKUP.BKP_BAIRRO (ID_BAIRRO, BAIRRO, ID_PAIS, ID_ESTADO, ID_CIDADE)
VALUES (NEW.ID_BAIRRO, NEW.BAIRRO, NEW.ID_PAIS, NEW.ID_ESTADO, NEW.ID_CIDADE);
END$$
DELIMITER ;

/* GATILHO DE BACKUP DA TABELA LISTA_PONTO */
DELIMITER $$
CREATE TRIGGER BKP_LISTA_PONTO
AFTER INSERT ON LISTA_PONTO
FOR EACH ROW
BEGIN
    INSERT INTO BACKUP.BKP_LISTA_PONTO (ID_PONTO, HORAS, DATA, ID_FUNCIONARIO)
    VALUES (NEW.ID_PONTO, NEW.HORAS, NEW.DATA, NEW.ID_FUNCIONARIO);
END$$
DELIMITER ;

/* GATILHO DE BACKUP DA TABELA PEDIDO */
DELIMITER $$
CREATE TRIGGER BKP_PEDIDO
AFTER INSERT ON PEDIDO
FOR EACH ROW
BEGIN
    INSERT INTO BACKUP.BKP_PEDIDO (ID_PEDIDO, VALOR_TOTAL, QUANT_ITENS, MESA, DATA, HORA, STATUS, ID_CLIENTE, ID_FUNCIONARIO)
    VALUES (NEW.ID_PEDIDO, NEW.VALOR_TOTAL, NEW.QUANT_ITENS, NEW.MESA, NEW.DATA, NEW.HORA, NEW.STATUS, NEW.ID_CLIENTE, NEW.ID_FUNCIONARIO);
END$$
DELIMITER ;

/* GATILHO DE BACKUP DA TABELA MOTO */
DELIMITER $$
CREATE TRIGGER BKP_MOTO
AFTER INSERT ON MOTO
FOR EACH ROW
BEGIN
    INSERT INTO BACKUP.BKP_MOTO (ID_MOTO, PLACA, RENAVAN, ANO_FABRICACAO, DATA_COMPRA)
VALUES (NEW.ID_MOTO, NEW.PLACA, NEW.RENAVAN, NEW.ANO_FABRICACAO, NEW.DATA_COMPRA);
END$$
DELIMITER ;

/* GATILHO DE BACKUP DA TABELA PAGAMENTO */
DELIMITER $$
CREATE TRIGGER BKP_PAGAMENTO
AFTER INSERT ON PAGAMENTO
FOR EACH ROW
BEGIN
INSERT INTO BACKUP.BKP_PAGAMENTO (ID_PAGAMENTO, TIPO_PAGAMENTO, VALOR_ENTREGA, VALOR_TOTAL, ID_PEDIDO)
VALUES (NEW.ID_PAGAMENTO, NEW.TIPO_PAGAMENTO, NEW.VALOR_ENTREGA, NEW.VALOR_TOTAL, NEW.ID_PEDIDO);
END$$
DELIMITER ;

/* GATILHO DE BACKUP DA TABELA MATERIA_PRIMA */
DELIMITER $$
CREATE TRIGGER BKP_MATERIA
AFTER INSERT ON MATERIA_PRIMA
FOR EACH ROW
BEGIN
INSERT INTO BACKUP.BKP_MATERIA_PRIMA (ID_MATERIA_PRIMA, NOME, DESCRICAO, QUANTIDADE, VALOR_MEDIO, TIPO)
VALUES (NEW.ID_MATERIA_PRIMA, NEW.NOME, NEW.DESCRICAO, NEW.QUANTIDADE, NEW.VALOR_MEDIO, NEW.TIPO);
END$$
DELIMITER ;

/* GATILHO DE BACKUP DA TABELA CATEGORIA */
DELIMITER $$
CREATE TRIGGER BKP_CATEGORIA
AFTER INSERT ON CATEGORIA
FOR EACH ROW
BEGIN
    INSERT INTO BACKUP.BKP_CATEGORIA (ID_CATEGORIA, NOME, DESCRICAO) VALUES (NEW.ID_CATEGORIA, NEW.NOME, NEW.DESCRICAO);
END$$

/* GATILHO DE BACKUP DA TABELA ITEM_MENU */
DELIMITER $$
CREATE TRIGGER BKP_ITEM_MENU
AFTER INSERT ON ITEM_MENU
FOR EACH ROW
BEGIN
    INSERT INTO BACKUP.BKP_ITEM_MENU (ID_ITEM_MENU, NOME, DESCRICAO, CAMINHO_IMAGEM, VALOR, ID_CATEGORIA) VALUES (NEW.ID_ITEM_MENU, NEW.NOME, NEW.DESCRICAO, NEW.CAMINHO_IMAGEM, NEW.VALOR, NEW.ID_CATEGORIA);
END$$

/* GATILHO DE BACKUP DA TABELA LISTA_PRODUTOS_PEDIDO */
DELIMITER $$
CREATE TRIGGER BKP_LISTA_PRODUTOS_PEDIDO
AFTER INSERT ON LISTA_PRODUTOS_PEDIDO
FOR EACH ROW
BEGIN
    INSERT INTO BACKUP.BKP_LISTA_PRODUTOS_PEDIDO (ID_LISTA_PRODUTOS_PEDIDO, ID_PEDIDO, ID_ITEM_MENU, QUANTIDADE, VALOR) VALUES (NEW.ID_LISTA_PRODUTOS_PEDIDO, NEW.ID_PEDIDO, NEW.ID_ITEM_MENU, NEW.QUANTIDADE, NEW.VALOR);
END$$

DELIMITER $$
CREATE TRIGGER BKP_ORDEM_COMPRA
AFTER INSERT ON ORDEM_COMPRA
FOR EACH ROW
BEGIN
    INSERT INTO BACKUP.BKP_ORDEM_COMPRA (ID_ORDEM_COMPRA, OBSERVACAO, QUANTIDADE_ITENS, VALOR_TOTAL, TIPO_PAGAMENTO, ID_FUNCIONARIO, ID_FORNECEDOR) VALUES (NEW.ID_ORDEM_COMPRA, NEW.OBSERVACAO, NEW.QUANTIDADE_ITENS, NEW.VALOR_TOTAL, NEW.TIPO_PAGAMENTO, NEW.ID_FUNCIONARIO, NEW.ID_FORNECEDOR);
END$$
