/*UTILIZADO PARA TESTES*/
DROP DATABASE IF EXISTS BAR_PETISCARIA_ARV_DATABASE_BACKUP;

/*CRIAR A DATABASE DO BAR*/
CREATE DATABASE IF NOT EXISTS BAR_PETISCARIA_ARV_DATABASE_BACKUP;
USE BAR_PETISCARIA_ARV_DATABASE_BACKUP;

/*CRIANDO TABELAS DE BACKUPS*/

/*TABELA GUARDA DADOS DOS FUNCIONARIOS */
CREATE TABLE IF NOT EXISTS FUNCIONARIO_BACKUP(
     ID_FUNCIONARIO_BACKUP INT PRIMARY KEY AUTO_INCREMENT,
     ID_FUNCIONARIO INT,
     NOME VARCHAR(50) NOT NULL,
     SOBRENOME VARCHAR(50) NOT NULL, 
	 DATA_NASCIMENTO DATE NOT NULL,
     SEXO ENUM('M','F') NOT NULL,
     CPF VARCHAR(15) NOT NULL UNIQUE,
     RG VARCHAR(15) NOT NULL UNIQUE,
     
     ACAO ENUM('INSERT', 'DELETE', 'UPDATE')
	 );
     

/*TABELA GUARDA DADOS DOS CLIENTES DA EMPRESA*/
CREATE TABLE IF NOT EXISTS CLIENTE_BACKUP(
     ID_CLIENTE_BACKUP INT PRIMARY KEY AUTO_INCREMENT,
     ID_CLIENTE INT,
     NOME VARCHAR(100) NOT NULL,
	 SOBRENOME VARCHAR(100) NOT NULL,
	 CPF VARCHAR(11) UNIQUE,
	 RG VARCHAR(15) NOT NULL,
	 DATA_NASCIMENTO DATE NOT NULL,
	 DATA_CADASTRO DATE NOT NULL, 
     SEXO ENUM('M','F') NOT NULL,
     
     ACAO ENUM('INSERT', 'DELETE', 'UPDATE')    
	 );
     
/*TABELA GUARDA AS INFORMACOES DOS FORNECEDORES*/
CREATE TABLE IF NOT EXISTS FORNECEDOR_BACKUP(
	ID_FORNECEDOR_BACKUP INT PRIMARY KEY AUTO_INCREMENT,
    ID_FORNECEDOR INT,
    RAZAO_SOCIAL VARCHAR(50) NOT NULL, 
    NOME_FANTASIA VARCHAR(50) NOT NULL,
    CNPJ VARCHAR(14) NOT NULL UNIQUE, 
    INSC_ESTADUAL VARCHAR(20) NOT NULL,
     
     ACAO ENUM('INSERT', 'DELETE', 'UPDATE')
);


CREATE TABLE IF NOT EXISTS TELEFONE_BACKUP(
	ID_TELEFONE_BACKUP INT PRIMARY KEY AUTO_INCREMENT,
    ID_TELEFONE INT,
    TELEFONE VARCHAR(25),
    B_CELULAR BOOL,
    B_WHATSAPP BOOL,
    
    ID_CLIENTE INT , 
    ID_FUNCIONARIO INT, 
    ID_FORNECEDOR INT,
     
     ACAO ENUM('INSERT', 'DELETE', 'UPDATE')
);

/*TABELA GUARDA OS EMAILS DA EMPRESA*/
CREATE TABLE IF NOT EXISTS EMAIL_BACKUP(
	ID_EMAIL_BACKUP INT PRIMARY KEY AUTO_INCREMENT,
    ID_EMAIL INT,
    EMAIL VARCHAR(25),
    
    ID_CLIENTE INT , 
    ID_FUNCIONARIO INT, 
    ID_FORNECEDOR INT,
     
     ACAO ENUM('INSERT', 'DELETE', 'UPDATE')
);

/*CRIANDO TRIGGERS DE BACKUP*/

CREATE TRIGGER BACKUP_INSERT_FUNCIONARIO
	AFTER INSERT ON BAR_PETISCARIA_ARV_DATABASE.FUNCIONARIO
    FOR EACH ROW 
    INSERT INTO BAR_PETISCARIA_ARV_DATABASE_BACKUP.FUNCIONARIO_BACKUP(ID_FUNCIONARIO_BACKUP, ID_FUNCIONARIO, ID_NOME, SOBRENOME, DATA_NASCIMENTO, SEXO, CPF, RG, ID_DEPARTAMENTO, ACAO)
    VALUE (ID_FUNCIONARIO_BACKUP, NEW.ID_FUNCIONARIO, NEW.NOME, NEW.SOBRENOME, NEW.DATA_NASCIMENTO, NEW.SEXO, NEW.CPF, NEW.RG, NEW.ID_DEPARTAMENTO, "INSERT");
    
    
    